server:
  port: 8761
eureka:
  instance:
    hostname: 18.179.108.227
  # client:
  #   registerWithEureka: false
  #   fetchRegistry: false
  serviceUrl:
    defaultZone: http://52.199.77.59:8761/eureka/