server:
  port: 8761
eureka:
  instance:
    hostname: 52.199.77.59
  # client:
  #   registerWithEureka: false
  #   fetchRegistry: false
  serviceUrl:
    defaultZone: http://18.179.108.227:8761/eureka/